services:
  - type: web
    name: mlproject
    env: python
    buildCommand: 
      - pip install -r requirements.txt
      - python setup.py install
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
